### ISSUE TITLE
Exiting due to channel error 

### ISSUE THREAD

**Issue by notyetasta** [re1san/K-Dots#12]
When reaching installing spotify and its config 
It exists due to channel error what to do
![image](https://github.com/re1san/K-Dots/assets/160411528/19bc10ac-a2e9-4775-a30a-e8a3e412cf2a)

**Comment by re1san** [comment]
Ahh, you can just ignore that and type 'y' to install spotify or 'n'. 
(Its basically the output of firefox, the script opens firefox and closes it. It is necessary for the installation of firefox config.)

**Comment by notyetasta** [comment]
Ok
